version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - "80:3000"
    depends_on:
      - db
      - message-broker
    environment:
      DATABASE_URL: mysql://bob4o:1000@db/bob4o-mysql
      MESSAGE_BROKER_URL: amqp://guest:guest@message-broker

  db:
    build:
      context: ./db

  message-broker:
    build:
      context: ./message_broker
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672"

